import "@radix-ui/themes/styles.css";
import "./globals.css";
import NavBar from "./NavBar";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { Inter } from "next/font/google";
import "./theme-config.css";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <QueryClientProvider>
        <AuthProvider>
          <Theme accentColor="lime">
          <NavBar/>
        <main className='p-5'>{children}</main>
        </Theme>
        </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}




// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

    // className={`${geistSans.variable} ${geistMono.variable} antialiased`}